apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: ui
        tier: frontend
    spec:
      containers:
        - name: ui
          image: docker.pkg.github.com/daniilor/stateless-hasher/ui:latest
          ports:
            - containerPort: 9999
      imagePullSecrets:
        - name: github-packages
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
    tier: frontend
  ports:
    - port: 80
---