apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
spec:
  selector:
    matchLabels:
      app: hasher
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: hasher
        tier: backend
    spec:
      containers:
        - name: hasher
          image: docker.pkg.github.com/daniilor/stateless-hasher/hasher:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-packages
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  selector:
    app: hasher
    tier: backend
  ports:
    - port: 9999